/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unesp.rc.webservicesoap.view;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Lucas
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() throws ParseException {
        initComponents();
        campoFormatado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCEP = new javax.swing.JFormattedTextField();
        btnConsultarCep = new javax.swing.JButton();
        lblEndereco = new javax.swing.JLabel();
        btnConsultarProcesso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atende Cliente");

        btnConsultarCep.setText("Consultar CEP");
        btnConsultarCep.setToolTipText("");
        btnConsultarCep.setName("btnConsultarCep"); // NOI18N
        btnConsultarCep.setOpaque(true);
        btnConsultarCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCepActionPerformed(evt);
            }
        });

        lblEndereco.setText("Endereço");
        lblEndereco.setName("lbEndereco"); // NOI18N

        btnConsultarProcesso.setText("Consultar Processo");
        btnConsultarProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProcessoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultarProcesso)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultarCep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarCep)
                    .addComponent(lblEndereco))
                .addGap(18, 18, 18)
                .addComponent(btnConsultarProcesso)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCepActionPerformed

        try { // Call Web Service Operation
            br.com.correios.bsb.sigep.master.bean.cliente.AtendeClienteService service
                    = new br.com.correios.bsb.sigep.master.bean.cliente.AtendeClienteService();
            br.com.correios.bsb.sigep.master.bean.cliente.AtendeCliente port = service.getAtendeClientePort();

            // TODO initialize WS operation arguments here
            java.lang.String cep = txtCEP.getText();

            // TODO process result here
            br.com.correios.bsb.sigep.master.bean.cliente.EnderecoERP result = port.consultaCEP(cep);

            // Exibir o resultado
            lblEndereco.setText(result.getCidade() + "/" + result.getUf() + " - " + result.getBairro() + " - " + result.getEnd());

        } catch (Exception e) {
            // TODO handle custom exceptions here
            JOptionPane.showMessageDialog(null, "Erro ao consultar WebService do Correios." + e, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarCepActionPerformed

    private void btnConsultarProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProcessoActionPerformed
        try { // Call Web Service Operation
            br.jus.cnj.servico_intercomunicacao_2_2.Servico service = new br.jus.cnj.servico_intercomunicacao_2_2.Servico();
            br.jus.cnj.servico_intercomunicacao_2_2.ServicoIntercomunicacao222 port = service.getServicoIntercomunicacao();
            
            // TODO initialize WS operation arguments here
            br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarProcesso consultarProcesso
                    = new br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarProcesso();
            
            // TODO process result here     
            consultarProcesso.setIdConsultante("############");
            consultarProcesso.setSenhaConsultante("########");
            consultarProcesso.setNumeroProcesso("0000546-46.2012.8.26.016");
            
            br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarProcessoResposta result
                    = port.consultarProcesso(consultarProcesso);
            
            System.out.println("Result = " + result);
        } catch (Exception ex) {
            // TODO handle custom exceptions here
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarProcessoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {  
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmPrincipal().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private void campoFormatado() throws ParseException {
        MaskFormatter Mask = new MaskFormatter("##.###-###");
        Mask.install(txtCEP);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarCep;
    private javax.swing.JButton btnConsultarProcesso;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JFormattedTextField txtCEP;
    // End of variables declaration//GEN-END:variables
}
